version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
